default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: db
  pool: 5

development:
  <<: *default
  database: houhealth_development

test:
  <<: *default
  database: houhealth_test

production:
  <<: *default
  database: houhealth_production
  username: <%= ENV['HOUHEALTH_DB_USER'] %>
  password: <%= ENV['HOUHEALTH_DB_PASS'] %>
